### ISSUE TITLE
Remove "create" link, add login link in footer

### ISSUE THREAD

**Issue by hanskhe** [magination/blog#39]
Remove the link to create a new blogpost from the site, move it to the footer when logged in. Put a discrete login link in the footer.

**Comment by JuulArthur** [comment]
I have removed create post link, but still need a link to login if we want that

**Comment by hanskhe** [comment]
I think the admins are able to log in on their own :wink: At least at the moment. 

Fixed in 8069d2fdcd9e4f002a84a2ebca5bc248fd162658
