### ISSUE TITLE
API-restriction for all set-methods

### ISSUE THREAD

**Issue by hanskhe** [magination/blog#5]
The API should not allow any set() calls for non-autorized users.

**Comment by hanskhe** [comment]
@tiborv What's the status on this? Is it possible for someone not logged in to write to the DB or get info they should not?

**Comment by tiborv** [comment]
https://github.com/magination/blog/blob/master/routes/index.js#L13
The functionality is present and working... It just needs to be uncommented.
Generally, all routes that use the middleware requireUser are protected.

**Comment by hanskhe** [comment]
Fixed by #31
